apiVersion: v1
kind: Service
metadata:
  name: chinmayee-svc-redis
  namespace: chinmayee
spec:
  selector:
    app: chinmayee-redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
              # default service type Exposes your redis pods inside the cluster as chinmayee-svc-redis:6379
              #Keeps it internal (ClusterIP). Only other pods inside the cluster (e.g., the vote app) can access it.S